version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker_files/go.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
